name: CD

on:
  push:
    branches:
      - main
      - p2p-testing

concurrency: cd-main

jobs:
  increment-version:
    uses: ./.github/workflows/increment-version.yaml
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
