name: CD

on:
  push:
    branches:
      - main


concurrency: cd-main

  
jobs:
  p2p:
    uses: ./.github/workflows/p2p.yaml
    with:
      project-id: PROJECT-ID
      project-number: PROJECT-NUMBER
      tenant-name: TEST-TENANT
      dry-run: true
  increment-version:
    uses: ./.github/workflows/increment-version.yaml
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
