name: CD

on:
  push:
    branches:
      - main

concurrency: cd-main

jobs:
  p2p:
    uses: ./.github/workflows/p2p.yaml
    with:
      dev-env-name: test-env
      prod-env-name: test-env
      dev-project-id: PROJECT-ID
      prod-project-id: PROJECT-ID
      dev-project-number: PROJECT-NUMBER
      prod-project-number: PROJECT-NUMBER
      tenant-name: TEST-TENANT
      dry-run: true
      pre-targets: test-pre-step
      post-targets: test-post-step

  increment-version:
    uses: ./.github/workflows/increment-version.yaml
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
