name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  increment-version:
    uses: ./.github/workflows/increment-version.yaml   
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
    with: 
      dry-run: true

  test_execute_command:
    uses: ./.github/workflows/execute-command.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      command: test-var-print
      workload-identity-provider: WORKLOAD_IP
      service-account: SERVICE_ACCOUNT
      project-id: TEST-TENANT
      dry-run: true

  test_execute_command_without_env_vars:
    uses: ./.github/workflows/execute-command.yaml
    with:
      command: p2p-build
      workload-identity-provider: WORKLOAD_IP
      service-account: SERVICE_ACCOUNT
      project-id: TEST-TENANT
      dry-run: true

  p2p:
    uses: ./.github/workflows/p2p.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      project-id: PROJECT-ID
      project-number: PROJECT-NUMBER
      tenant-name: TEST-TENANT
      dry-run: true

