name: CI

on:
  pull_request:
    branches:
      - main
      - initial-p2p

jobs:
  increment-version:
    uses: ./.github/workflows/increment-version.yaml   
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
    with: 
      dry-run: true

  test_execute_command:
    needs: [build, setup]
    uses: c./.github/workflows/execute-command.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      command: p2p-build
      workload-identity-provider: WORKLOAD_IP
      service-account: SERVICE_ACCOUNT
      project-id: TEST-TENANT
      dry-run: true
      
  test_execute_command_without_env_vars:
    needs: [build, setup]
    uses: c./.github/workflows/execute-command.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      command: p2p-build
      workload-identity-provider: WORKLOAD_IP
      service-account: SERVICE_ACCOUNT
      project-id: TEST-TENANT
      dry-run: true

  p2p:
    uses: ./.github/workflows/idp-p2p.yaml
    with:
      project-id: PROJECT-ID
      project-number: PROJECT-NUMBER
      tenant-name: TEST-TENANT
      dry-run: true

