name: IDP P2P

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
      project-number:
        required: true
        type: string
      tenant-name:
        required: true
        type: string
      dry-run:
        required: false
        type: boolean
        default: false

env:
  REGISTRY: europe-west2-docker.pkg.dev/${{ inputs.project-id }}/tenant
  SERVICE_ACCOUNT: p2p-${{ inputs.tenant-name }}@${{ inputs.project-id }}.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ inputs.project-number }}/locations/global/workloadIdentityPools/p2p-${{ inputs.tenant-name }}/providers/p2p-${{ inputs.tenant-name }}


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      workflow_identity_provider: ${{ steps.setup.outputs.workflow_identity_provider }}
      service_account: ${{ steps.setup.outputs.service_account }}
    steps:   
      - name: Setup inputs passed to the reusable workflow
        id: setup
        run: |
          echo "workflow_identity_provider=$WORKLOAD_IDENTITY_PROVIDER" >> $GITHUB_OUTPUT
          echo "service_account=$SERVICE_ACCOUNT" >> $GITHUB_OUTPUT
  build:
    needs: [setup]
    uses: ./.github/workflows/execute-command.yaml
    with:
      command: p2p-build
      workload-identity-provider: ${{ needs.setup.outputs.workflow_identity_provider }}
      service-account: ${{ needs.setup.outputs.service_account }}
      project-id: ${{ inputs.project-id }}
      dry-run: ${{ inputs.dry-run }}

  functional-test:
    needs: [build, setup]
    uses: ./.github/workflows/execute-command.yaml
    with:
      command: p2p-functional
      workload-identity-provider: ${{ needs.setup.outputs.workflow_identity_provider }}
      service-account: ${{ needs.setup.outputs.service_account }}
      project-id: ${{ inputs.project-id }}
      dry-run: ${{ inputs.dry-run }}

  nft-test:
    name: nft-test
    needs: [functional-test, setup]
    uses: ./.github/workflows/execute-command.yaml
    with:
      command: p2p-nft
      workload-identity-provider: ${{ needs.setup.outputs.workflow_identity_provider }}
      service-account: ${{ needs.setup.outputs.service_account }}
      project-id: ${{ inputs.project-id }}
      dry-run: ${{ inputs.dry-run }}

  dev-deploy:
    name: dev-deploy
    needs: [nft-test, setup]
    if: github.ref_name == 'main'
    uses: ./.github/workflows/execute-command.yaml
    with:
      command: p2p-dev
      workload-identity-provider: ${{ needs.setup.outputs.workflow_identity_provider }}
      service-account: ${{ needs.setup.outputs.service_account }}
      project-id: ${{ inputs.project-id }}
      dry-run: ${{ inputs.dry-run }}
