name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  increment-version:
    uses: ./.github/workflows/internal-version.yaml
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      dry-run: true

  print-version:
    runs-on: ubuntu-latest
    needs: increment-version
    steps:
      - env:
          VERSION: ${{needs.increment-version.outputs.version}}
        id: step1
        run: echo "The Next Version is $VERSION"

  test_version:
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      dry-run: true
      version-prefix: app-tag
    uses: ./.github/workflows/p2p-version.yaml

  test_version_default :
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      dry-run: true
    uses: ./.github/workflows/p2p-version.yaml
    
  test_execute_command:
    needs: [test_version]
    uses: ./.github/workflows/p2p-execute-command.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      command: test-var-print
      dry-run: true
      version: ${{ needs.test_version.outputs.version }}

  test_fastfeedback:
    needs: [test_version]
    uses: ./.github/workflows/p2p-workflow-fastfeedback.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      dry-run: true
      version: ${{ needs.test_version.outputs.version }}

  get_image_extended_test:
    uses: ./.github/workflows/p2p-get-latest-image-extended-test.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      dry-run: true
      main-branch: ${{ github.ref }}
      image-name: p2p

  test_extended_test:
    uses: ./.github/workflows/p2p-workflow-extended-test.yaml
    needs: [get_image_extended_test] 
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      dry-run: true
      main-branch: ${{ github.ref }}
      version: ${{ needs.get_image_extended_test.outputs.version }}

  get_image_prod:
    uses: ./.github/workflows/p2p-get-latest-image-prod.yaml
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      dry-run: true
      main-branch: ${{ github.ref }}
      image-name: p2p

  test_prod:
    uses: ./.github/workflows/p2p-workflow-prod.yaml
    needs: [get_image_prod]
    secrets:
      env_vars: |
        TEST_VARIABLE=value
    with:
      dry-run: true
      main-branch: ${{ github.ref }}
      version: ${{ needs.get_image_prod.outputs.version }}
