
on:
  workflow_call:
    inputs:
      source:
        required: false
        type: string
        default: ${{ vars.EXTENDED_TEST }}
      destination:
        required: false
        type: string
        default: ${{ vars.PROD }}
      dry-run:
        required: false
        type: boolean
        default: false
      image_tag:
        required: false
        type: string
        default: ''
      semver:
        required: false
        type: string
        default: ''
      region:
        required: false
        type: string
        default: europe-west2

env:
  REGION: ${{ inputs.region }} 

jobs:
  run-tests:
    uses: ./.github/workflows/p2p-execute-command.yaml
    strategy:
      matrix: ${{ fromJSON(inputs.source ) }}
      fail-fast: false
    with:
      command: p2p-extended-tests
      github_env: ${{ matrix.deploy_env }}
      image_tag: ${{ inputs.image_tag }}
      semver: ${{ inputs.semver }}

  promote:
    uses: ./.github/workflows/p2p-promote-image.yaml
    needs: [run-tests]
    strategy:
      matrix: ${{ fromJSON(inputs.destination) }}
      fail-fast: false
    with:
      source_matrix: ${{ inputs.source }}
      dest_github_env: ${{ matrix.deploy_env }}
      promotion-stage: prod
      image_tag: ${{ inputs.image_tag }}
      semver: ${{ inputs.semver }}
