
on:
  workflow_call:
    inputs:
      stage-dev:
        required: false
        type: string
        default: ${{ vars.STAGE_DEV }}
      stage-prod:
        required: false
        type: string
        default: ${{ vars.STAGE_PROD }}
      dry-run:
        required: false
        type: boolean
        default: false
      image_tag:
        required: false
        type: string
        default: ''
      semver:
        required: false
        type: string
        default: ''
      pre-targets:
        description: |
          Make targets to run before each p2p command
        required: false
        type: string
        default: ''
      post-targets:
        description: |
          Make targets to run after each p2p command
        required: false
        type: string
        default: ''

env:
  REGION: europe-west2

jobs:
  run-tests:
    needs: [promote-pre-extended-tests]
    if: inputs.stage-dev != ''
    #if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/p2p-execute-command.yaml
    strategy:
      matrix: ${{ fromJSON(inputs.stage-dev) }}
      fail-fast: false
    with:
      command: p2p-extended-tests
      github_env: ${{ matrix.deploy_env }}
      image_tag: ${{ inputs.image_tag }}
      semver: ${{ inputs.semver }}

  promote-post-extended-tests:
    uses: ./.github/workflows/p2p-promote-image.yaml
    needs: [run-tests]
    if: inputs.stage-prod != ''
    strategy:
      matrix: ${{ fromJSON(inputs.stage-prod) }}
      fail-fast: false
    with:
      source_matrix: ${{ inputs.stage-dev }}
      dest_github_env: ${{ matrix.deploy_env }}
      promotion-stage: prod
      image_tag: ${{ inputs.image_tag }}
      semver: ${{ inputs.semver }}
