
on:
  workflow_call:
    secrets:
      env_vars:
        required: false
    inputs:
      source:
        required: false
        type: string
        default: ${{ vars.EXTENDED_TEST }}
      destination:
        required: false
        type: string
        default: ${{ vars.PROD }}
      dry-run:
        required: false
        type: boolean
        default: false
      version:
        required: false
        type: string
        default: ''
      region:
        required: false
        type: string
        default: europe-west2

env:
  REGION: ${{ inputs.region }} 

jobs:
  run-tests:
    uses: ./.github/workflows/p2p-execute-command.yaml
    secrets:
      env_vars: ${{ secrets.env_vars }}
    strategy:
      matrix: ${{ fromJSON(inputs.source ) }}
      fail-fast: false
    with:
      command: p2p-extended-test
      github_env: ${{ matrix.deploy_env }}
      version: ${{ imputs.version }}

  promote:
    uses: ./.github/workflows/p2p-promote-image.yaml
    needs: [run-tests]
    secrets:
      env_vars: ${{ secrets.env_vars }}
    strategy:
      matrix: ${{ fromJSON(inputs.destination) }}
      fail-fast: false
    with:
      source_matrix: ${{ inputs.source }}
      dest_github_env: ${{ matrix.deploy_env }}
      promotion-stage: prod
      version: ${{ imputs.version }}
