
on:
  workflow_call:
    secrets:
      env_vars:
        required: false
    inputs:
      source:
        required: false
        type: string
        default: ${{ vars.FAST_FEEDBACK}}
      destination:
        required: false
        type: string
        default: ${{ vars.EXTENDED_TEST }}
      dry-run:
        required: false
        type: boolean
        default: false
      main-branch:
        required: false
        type: string
        default: 'refs/heads/main'
      version: 
        required: true
        type: string
      region:
        required: false
        type: string
        default: europe-west2
    outputs:
      version:
        value: ${{ inputs.version }}


env:
  REGION: ${{ inputs.region }} 

jobs:
  build:
    uses: ./.github/workflows/p2p-execute-command.yaml
    secrets:
      env_vars: ${{ secrets.env_vars }}
    strategy:
      matrix: ${{ fromJSON(inputs.source) }}
      fail-fast: false
    with:
      command: p2p-build
      github_env: ${{ matrix.deploy_env }}
      version: $${{ inputs.version }}

  functional-test:
    needs: [build]
    uses: ./.github/workflows/p2p-execute-command.yaml
    secrets:
      env_vars: ${{ secrets.env_vars }}
    strategy:
      matrix: ${{ fromJSON(inputs.source) }}
      fail-fast: false
    with:
      command: p2p-functional
      github_env: ${{ matrix.deploy_env }}
      version: ${{ inputs.version }}


  nft-test:
    needs: [version, functional-test]
    uses: ./.github/workflows/p2p-execute-command.yaml
    secrets:
      env_vars: ${{ secrets.env_vars }}
    strategy:
      matrix: ${{ fromJSON(inputs.source) }}
      fail-fast: false
    with:
      command: p2p-nft
      github_env: ${{ matrix.deploy_env }}
      version: ${{ inputs.version }}

  promote:
    name: promote
    needs: [nft-test, functional-test]
    if: github.ref == ${{ inputs.main-branch }} 
    secrets:
      env_vars: ${{ secrets.env_vars }}
    uses: ./.github/workflows/p2p-promote-image.yaml
    strategy:
      matrix: ${{ fromJSON(inputs.destination) }}
      fail-fast: false
    with:
      source_matrix: ${{ inputs.source }}
      dest_github_env: ${{ matrix.deploy_env }}
      promotion-stage: extended-tests
      version: ${{ inputs.version }}


