name: increment-version

on:
  workflow_call:
    outputs:
      version:
        description: "The next semantic version"
        value: ${{ jobs.increment-version.outputs.version }}
      previous_version:
        description: "The previous version"
        value: ${{ jobs.increment-version.outputs.previous_version }}
    secrets:
      git-token:
        required: true
    inputs:
      main-branch:
        required: false
        type: string
        default: 'refs/heads/main'
      dry-run:
        type: boolean
        required: false
        default: false
      version-prefix:
        required: false
        type: string
        default: 'v'
      

jobs:
  increment-version:
    name: increment-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setversion.outputs.version }}
      previous_version: ${{ steps.setversion.outputs.previous_version }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"    

    - name: Get Previous tag
      id: previoustag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.git-token }}
        VERSION_PREFIX: ${{ inputs.version-prefix }}
      run: |
        REGEX=$(echo "^${VERSION_PREFIX}([0-9]+)\.([0-9]+)\.([0-9]+)$")
        PREVIOUS_VERSION=$(git tag | sort -r --version-sort | grep -E ${REGEX} || echo "" | head -n1 )
        [ -z "$PREVIOUS_VERSION" ] && PREVIOUS_VERSION=${VERSION_PREFIX}0.0.0
        echo "tag=$PREVIOUS_VERSION" >> "$GITHUB_OUTPUT" 
      

    - name: get previous version from tag
      id: previousversion
      shell: bash
      env:
        VERSION_PREFIX: ${{ inputs.version-prefix }}
      run: |
        echo "version=$(echo ${{ steps.previoustag.outputs.tag }} | awk -F ${VERSION_PREFIX} '{print $2}')" >> "$GITHUB_OUTPUT"

    - name: Get next patch version
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previousversion.outputs.version }} 

    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      if: success() && (github.ref == inputs.main-branch && inputs.dry-run == false)
      id: create_tag
      with:
        tag: ${{ inputs.version-prefix }}${{ steps.semvers.outputs.patch }}
        tag_exists_error: true

    - name: Set bumped version in ourput
    - name: Set bumped version in output
      id: setversion
      shell: bash
      run: |
        set -x
        env
        if [ "${{ inputs.main-branch }}" = "${{ github.ref }}" ]; then
          echo "On main branch, setting next version"
          echo "version=${{ steps.semvers.outputs.patch }}" >> "$GITHUB_OUTPUT"
        else
          echo "Not on main branch, setting previous version + hash"
          HASH=$(git rev-parse --short HEAD)
          echo "version=${{ steps.previousversion.outputs.version }}-$HASH" >> "$GITHUB_OUTPUT"
        fi
        echo "previous_version=${{ steps.previousversion.outputs.version }}" >> "$GITHUB_OUTPUT"

