name: Environment Feature Matrix

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      matrix:
        value: ${{ jobs.generate.outputs.matrix }}

jobs:
  generate:
    name: generate
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: generate-matrix
        name: Generate Matrix
        run: |
          # generate matrix
          for f in $(yq '.features' environments/${{ inputs.environment }}/config.yaml -o csv | tr "," " ") ; do
            e+="{\"feature\":\"${f}\"},"
          done
          MATRIX="$(printf '{"include":[%s]}' "${e}")"
          echo "${MATRIX}" | yq -o json
          echo "matrix=${MATRIX}" >> "${GITHUB_OUTPUT}"
