name: Developer Platform CI

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      platform:
        type: string
        required: true
      release:
        type: string
        required: true
    secrets:
      cecg-registry-username:
        required: true
      cecg-registry-secret:
        required: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    outputs:
      tenants: ${{ steps.filter.outputs.tenants }}
      environments: ${{ steps.filter.outputs.environments }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tenants:
              - 'tenants/**'
            environments:
              - 'environments/**'

  tenants:
    name: tenants
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [changes]
    if: ${{ needs.changes.outputs.tenants == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: validate
      targets: tenants-validate
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  connected-kubernetes:
    name: connected-kubernetes
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [changes]
    if: ${{ needs.changes.outputs.environments == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      feature: connected-kubernetes
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  infra-operator:
    name: infra-operator
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [connected-kubernetes, changes]
    if: ${{ needs.changes.outputs.environments == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      feature: infra-operator
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  multi-tenant-kubernetes-access:
    name: multi-tenant-kubernetes-access
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [infra-operator, changes]
    if: ${{ needs.changes.outputs.environments == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      targets: helm-package
      feature: multi-tenant-kubernetes-access
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  tenants-yaml:
    name: tenants-yaml
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [multi-tenant-kubernetes-access, tenants, changes]
    if: ${{ always() && !failure() && !cancelled() && needs.changes.outputs.tenants == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      feature: tenants-yaml
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  platform-monitoring:
    name: platform-monitoring
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [tenants-yaml, connected-kubernetes]
    if: ${{ always() && !failure() && !cancelled() && needs.changes.outputs.environments == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      feature: platform-monitoring
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  platform-ingress:
    name: platform-ingress
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [tenants-yaml, connected-kubernetes]
    if: ${{ always() && !failure() && !cancelled() && needs.changes.outputs.environments == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      feature: platform-ingress
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}
