name: Environment Matrix

on:
  workflow_call:
    outputs:
      matrix:
        value: ${{ jobs.generate.outputs.matrix }}

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: generate-matrix
        name: Generate Matrix
        run: |
          # generate matrix
          for f in environments/*/config.yaml ; do
            [ -e "${f}" ] && e+="{\"environment\":\"$(yq .environment "${f}")\",\"platform\":\"$(yq .platform.vendor "${f}")\",\"release\":\"$(yq .release "${f}")\"},"
          done
          MATRIX="$(printf '{"include":[%s]}' "${e}")"
          echo "${MATRIX}" | yq -o json
          echo "matrix=${MATRIX}" >> "${GITHUB_OUTPUT}"
