name: Developer Platform CD

on:
  workflow_call:
    secrets:
      cecg-docker-username:
        required: true
      cecg-docker-secret:
        required: true

jobs:
  matrix:
    name: Matrix
    uses: coreeng/p2p/.github/workflows/platform-environment-matrix.yml@main

  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    outputs:
      tenants: ${{ steps.filter.outputs.tenants }}
      environments: ${{ steps.filter.outputs.environments }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tenants:
              - 'tenants/**'
            environments:
              - 'environments/**'

  tenants:
    name: tenants
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, changes]
    if: ${{ needs.changes.outputs.tenants == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: validate
      targets: tenants-validate
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}

  connected-kubernetes:
    name: connected-kubernetes
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, changes]
    if: ${{ needs.changes.outputs.environments == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: features-apply
      feature: connected-kubernetes
      post-targets: cluster-prewarm
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}

  infra-operator:
    name: infra-operator
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, connected-kubernetes, changes]
    if: ${{ needs.changes.outputs.environments == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: features-apply
      feature: infra-operator
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}


  multi-tenant-kubernetes-access:
    name: multi-tenant-kubernetes-access
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, infra-operator, changes]
    if: ${{ needs.changes.outputs.environments == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: features-apply
      targets: helm-push
      feature: multi-tenant-kubernetes-access
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}

  tenants-yaml:
    name: tenants-yaml
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, multi-tenant-kubernetes-access, tenants, changes]
    if: ${{ always() && !failure() && !cancelled() }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: features-apply
      feature: tenants-yaml
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}

  platform-monitoring:
    name: platform-monitoring
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, tenants-yaml, changes]
    if: ${{ always() && !failure() && !cancelled() && needs.changes.outputs.environments == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: features-apply
      feature: platform-monitoring
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}

  platform-ingress:
    name: platform-ingress
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [matrix, tenants-yaml, changes]
    if: ${{ always() && !failure() && !cancelled() && needs.changes.outputs.environments == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    secrets:
      registry-username: ${{ secrets.cecg-docker-username }}
      registry-secret: ${{ secrets.cecg-docker-secret }}
    with:
      action: features-apply
      feature: platform-ingress
      environment: ${{ matrix.environment }}
      platform: ${{ matrix.platform }}
      release: ${{ matrix.release }}
