name: Developer Platform CI

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      platform:
        type: string
        required: true
      release:
        type: string
        required: true
      release_build:
        type: boolean
        default: false
        required: false
    secrets:
      cecg-registry-username:
        required: true
      cecg-registry-secret:
        required: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    outputs:
      tenants: ${{ steps.filter.outputs.tenants }}
      environments: ${{ steps.filter.outputs.environments }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            tenants:
              - 'tenants/**'
            environments:
              - 'environments/**'

  tenants-validate:
    name: tenants
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: validate
      targets: tenants-validate
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  matrix:
    name: Matrix
    needs: [changes]
    uses: ./.github/workflows/platform-environment-feature-matrix.yaml
    with:
      environment: ${{ inputs.environment }}

  feature:
    name: Feature
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [changes, matrix]
    if: ${{ inputs.release_build == true || needs.changes.outputs.environments == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    with:
      action: features-plan
      feature: ${{ matrix.feature }}
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}

  tenants-plan:
    name: tenants-yaml
    uses: coreeng/p2p/.github/workflows/platform-execute-command.yaml@main
    needs: [tenants-validate, changes]
    if: ${{  inputs.release_build == false && needs.changes.outputs.environments != 'true' && needs.changes.outputs.tenants == 'true' }}
    secrets:
      cecg-registry-username: ${{ secrets.cecg-registry-username }}
      cecg-registry-secret: ${{ secrets.cecg-registry-secret }}
    with:
      action: features-plan
      feature: tenants-yaml
      environment: ${{ inputs.environment }}
      platform: ${{ inputs.platform }}
      release: ${{ inputs.release }}
      

