name: Environment Matrix

on:
  workflow_call:
    inputs:
      include_release:
        required: false
        default: true
        type: boolean
      branch_filter:
        required: false
        default: 'main'
        type: string
    outputs:
      matrix:
        value: ${{ jobs.generate.outputs.matrix }}

jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: generate-matrix
        name: Generate Matrix
        run: |
          # generate matrix
          for f in environments/*/config.yaml ; do
            if [ -e "${f}" ] ; then
              if ! [ "${BRANCH_FILTER}" ] || [ "$(echo "${MATRIX_ENV_BRANCHES}" | jq -r '.[] | select(.environment == "'"$(yq .environment "${f}")"'") | .branch')" = "${BRANCH_FILTER}" ] ; then
                if "${INCLUDE_RELEASE}" ; then
                  e+="{\"environment\":\"$(yq .environment "${f}")\",\"platform\":\"$(yq .platform.vendor "${f}")\",\"release\":\"$(yq .release "${f}")\"},"
                else
                  e+="{\"environment\":\"$(yq .environment "${f}")\",\"platform\":\"$(yq .platform.vendor "${f}")\"},"
                fi
              fi
            fi
          done
          MATRIX="$(printf '{"include":[%s]}' "${e}")"
          echo "${MATRIX}" | yq -o json
          echo "matrix=${MATRIX}" >> "${GITHUB_OUTPUT}"
